services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ../project:/var/www
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'laravel'
      POSTGRES_USER: 'laravel'
      POSTGRES_PASSWORD: 'secret'

    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network
  nginx:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ../project:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
